language: cpp
env:
  global:
  - INSTALL_DIR="sfizz-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}-${TRAVIS_CPU_ARCH}"

jobs:
  include:
  - os:   linux
    env:
    - CROSS_COMPILE=mingw32
    - CONTAINER=cross

  - os:   linux
    env:
    - CROSS_COMPILE=mingw64
    - CONTAINER=cross

  - os:   linux
    arch: amd64
    dist: bionic
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'deb-src http://archive.ubuntu.com/ubuntu bionic main restricted'
        - sourceline: 'deb-src http://archive.ubuntu.com/ubuntu bionic-updates main restricted'
        - sourceline: 'deb-src http://archive.ubuntu.com/ubuntu bionic-security main restricted'
        packages:
        - doxygen

  - os:   linux
    arch: arm64
    dist: bionic
    addons:
      apt:
        sources:
        - sourceline: 'ppa:ubuntu-toolchain-r/test'
        - sourceline: 'deb-src http://ports.ubuntu.com/ubuntu-ports bionic main restricted'
        - sourceline: 'deb-src http://ports.ubuntu.com/ubuntu-ports bionic-updates main restricted'
        - sourceline: 'deb-src http://ports.ubuntu.com/ubuntu-ports bionic-security main restricted'

  - os: osx
    osx_image: xcode10.1

  - os:   linux
    env:
    - BUILD_TYPE=source
    - INSTALL_DIR="sfizz-${TRAVIS_BRANCH}-src"
    addons:
      apt:
        packages:
        - python-pip

    before_install:
    - true

    install:
    - sudo pip install git-archive-all

    script:
    - git-archive-all --prefix="sfizz-${TRAVIS_BRANCH}/" -9 "${INSTALL_DIR}.tar.gz"

    after_failure:
    - true

    after_success:
    - true

before_install:
- bash ${TRAVIS_BUILD_DIR}/.travis/before_install.sh

install:
- bash ${TRAVIS_BUILD_DIR}/.travis/install.sh

script:
- bash ${TRAVIS_BUILD_DIR}/.travis/script.sh

after_failure:
- bash ${TRAVIS_BUILD_DIR}/.travis/discord_webhook.sh failure

after_success:
- bash ${TRAVIS_BUILD_DIR}/.travis/discord_webhook.sh success
- bash ${TRAVIS_BUILD_DIR}/.travis/update_dox.sh
- bash ${TRAVIS_BUILD_DIR}/.travis/after_success.sh

deploy:
  provider:     releases
  skip_cleanup: true
  file:         "${INSTALL_DIR}.tar.gz"
  token:
    secure: jBIMWMPva8OazC8Wnqc2vqATa3exjvGDGvejEu6fgwt/BMDkgJCsJ7gS3ITpYFuO0HoHtLGfTVrFcZIE+agGVRdRGRni5xZRp5Vuf9hvLf8hCTaxkS/HYoliYYPp9FLY6J4yq9mp/R/QyGrwgssQEjhYlI2GL4+lJzt750AcmYibnQo2AMe5SSOp3q8KdLBG1vca1o1BZWBhW/S7l2hA1aJ7y1ytwm0ETIdrTZHxgfz7bqdqQcw/Ytqjm1rgzty6iQKX3B/InaZNB6CqXy6FoGLf771lery8nWJbjTjKYD4QK2NelExldyp1vrdHGvknWguFk+8vlQ16Dt0+R7Byr/LOPRLTCf/T+IehMQGtVA9/gjrkH8LqHy9oVFB+33p11gGu3h6hvg7yB6z3sSck0u4FHjrlpNd5XmmCsKQVQ9vI1cPPkVkbMHIewc7uOu+bD6cmotFj1vJ9UYesvN6n4siyCiPOIhgV9++bjcyiLqX3DWP5UWyZ9/VT8bz5VcxUdJnEYtdNPx4x5pRW4081VUjIf2EmHhQTrjb1iz6FAGwNU/fpefA8x+bBxXP9MkFFgU0tbCDKw2y6o0GOXX82mZr/IB0/DIBg7UllTzCBKTuiJQV1prFPlZLc6V22H5ozAXHgu3E+qNjvHoMsoYjGssX3+AYHwu8isBINo/gGo6Y=
  on:
    repo: ${TRAVIS_REPO_SLUG}
    tags: true

notifications:
  irc:
    channels:
    - "ircs://chat.freenode.net:7070/#sfztools"

    template:
    - "[%{repository_name}:%{branch}] Build #%{build_number}: %{message}"
    - "%{author} : %{commit_subject}"
    - "Commit URL    : https://github.com/%{repository_slug}/commit/%{commit}"
    - "Build Details : %{build_url}"
