version: build-{build}
image: Visual Studio 2017
configuration: Release
platform:
- Win32
- x64

install:
- cmd: if %platform%==Win32 set VCPKG_TRIPLET=x86-windows-static
- cmd: if %platform%==x64   set VCPKG_TRIPLET=x64-windows-static
- cmd: vcpkg install libsndfile:%VCPKG_TRIPLET%

before_build:
- cmd: git submodule update --init
- cmd: mkdir CMakeBuild
- cmd: cd CMakeBuild
- cmd: if %platform%==Win32 set CMAKE_GENERATOR=Visual Studio 15 2017
- cmd: if %platform%==x64   set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
- cmd: cmake .. -G"%CMAKE_GENERATOR%" -DSFIZZ_JACK=OFF -DSFIZZ_BENCHMARKS=OFF -DSFIZZ_TESTS=OFF -DSFIZZ_LV2=ON -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=%VCPKG_TRIPLET% -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake

build_script:
- cmd: cmake --build . --config Release -j

after_build:
- cmd: cp sfizz.lv2/Release/sfizz.dll sfizz.lv2/
- cmd: rm -rf sfizz.lv2/Release
- cmd: if %platform%==Win32 set RELEASE_ARCH=x86
- cmd: if %platform%==x64   set RELEASE_ARCH=x64
- cmd: 7z a sfizz-%APPVEYOR_REPO_TAG_NAME%-%RELEASE_ARCH%-msvc-lv2.zip sfizz.lv2
- cmd: 7z a sfizz-%APPVEYOR_REPO_TAG_NAME%-%RELEASE_ARCH%-msvc-library.zip src/Release/sfizz*

artifacts:
- name: Packages
  path: 'CMakeBuild/sfizz*.zip'

